// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRisk.Infrastructure.Data;

#nullable disable

namespace VendorRisk.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VendorDbContext))]
    partial class VendorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRisk.Domain.Models.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlaUptime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("vendor_profiles", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Models.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRisk.Domain.Models.VendorDocuments", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("contract_valid");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("pentest_report_valid");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_policy_valid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("vendor_profiles");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
